#!/bin/sh

# ===============================
# TTL 优化（轻量稳定版）
# ===============================

iptables -t mangle -A POSTROUTING -j TTL --ttl-set 65

# 保存防火墙
uci commit firewall

# 删除自身
rm -f /etc/uci-defaults/99-ttl-optimize

exit 0
