name: ImmortalWrt Stable Build

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  TZ: Asia/Shanghai
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Clean space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android || true

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk git \
          libncurses5-dev libssl-dev python3 rsync unzip wget curl

      - name: Clone OpenWrt
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt

      - name: Feeds
        run: |
          cp feeds.conf.default openwrt/feeds.conf.default
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy files
        run: |
          cp -r files openwrt/
          cp .config openwrt/
          cp diy-part1.sh openwrt/
          cp diy-part2.sh openwrt/

      - name: Fix permissions
        run: |
          chmod +x openwrt/diy-part1.sh
          chmod +x openwrt/diy-part2.sh
          chmod +x openwrt/files/etc/uci-defaults/99-proxy-init || true

      - name: Build prepare
        run: |
          cd openwrt
          ./diy-part1.sh
          make defconfig

      - name: Download
        run: |
          cd openwrt
          make download -j8

      - name: Build
        run: |
          cd openwrt
          make -j$(nproc) || make -j1 V=s

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-Stable
          path: openwrt/bin
